### ISSUE TITLE
Error Running Train.py

### ISSUE THREAD

**Issue by mitchross** [vietnguyen91/Flappy-bird-deep-Q-learning-pytorch#6]
Flappy-bird-deep-Q-learning-pytorch/src/deep_q_network.py:21: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  nn.init.uniform(m.weight, -0.01, 0.01)
Perform a random action
Iteration: 2/2000000, Action: 1, Loss: 0.010123813524842262, Epsilon 0.1, Reward: 0.1, Q-value: 0.0005683371564373374
Traceback (most recent call last):
  File "train.py", line 133, in <module>
    train(opt)
  File "train.py", line 74, in train
    action = torch.argmax(prediction)[0]
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number
(python36) bash-3.2$

**Comment by 2448845600** [comment]
I meet the question so. It cause bytorch version. In latest torch, 0-dim tensor is invaild, 
我也遇到这问题，是torch版本引起的，稍作修改即可。

Change code line77

`       
action = torch.argmax(prediction)[0]
`     

To

`        
 action = torch.argmax(prediction)
`

**Comment by mitchross** [comment]
I tried that. Still errors

(python36) C:\Flappy-bird-deep-Q-learning-pytorch>python train.py
Traceback (most recent call last):
  File "train.py", line 15, in <module>
    from src.flappy_bird import FlappyBird
  File "C:\***\Flappy-bird-deep-Q-learning-pytorch\src\flappy_bird.py", line 6, in <module>
    from pygame import Rect, init, time, display
  File "C:\Users\**\**\**\**\lib\site-packages\pygame\__init__.py", line 120, in <module>
    from pygame.base import *
ModuleNotFoundError: No module named 'pygame.base'

**Comment by Jarvis-Cai** [comment]
@2448845600 thanks, guy! fix my problem.

**Comment by xueliu8617112** [comment]
@2448845600 谢谢~搞定啦
